# Generated by Django 4.0.10 on 2023-05-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='PositiveThing',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
